/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/ChooseModeScreen`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/register`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/Driver/DriverHomePage`; params?: Router.UnknownInputParams; } | { pathname: `/Driver/DriverOnTravel`; params?: Router.UnknownInputParams; } | { pathname: `/Driver/DriverTravel`; params?: Router.UnknownInputParams; } | { pathname: `/Driver/PublishTravel`; params?: Router.UnknownInputParams; } | { pathname: `/Driver/RequestTravelDriver`; params?: Router.UnknownInputParams; } | { pathname: `/Passenger/PassengerConfirmation`; params?: Router.UnknownInputParams; } | { pathname: `/Passenger/PassengerConfirmRider`; params?: Router.UnknownInputParams; } | { pathname: `/Passenger/PassengerDriverProfile`; params?: Router.UnknownInputParams; } | { pathname: `/Passenger/PassengerHomePage`; params?: Router.UnknownInputParams; } | { pathname: `/Passenger/PassengerOnTravel`; params?: Router.UnknownInputParams; } | { pathname: `/Passenger/Passengerrideroffers`; params?: Router.UnknownInputParams; } | { pathname: `/Passenger/PassengerSearchRider`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/ChooseModeScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/register`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/Driver/DriverHomePage`; params?: Router.UnknownOutputParams; } | { pathname: `/Driver/DriverOnTravel`; params?: Router.UnknownOutputParams; } | { pathname: `/Driver/DriverTravel`; params?: Router.UnknownOutputParams; } | { pathname: `/Driver/PublishTravel`; params?: Router.UnknownOutputParams; } | { pathname: `/Driver/RequestTravelDriver`; params?: Router.UnknownOutputParams; } | { pathname: `/Passenger/PassengerConfirmation`; params?: Router.UnknownOutputParams; } | { pathname: `/Passenger/PassengerConfirmRider`; params?: Router.UnknownOutputParams; } | { pathname: `/Passenger/PassengerDriverProfile`; params?: Router.UnknownOutputParams; } | { pathname: `/Passenger/PassengerHomePage`; params?: Router.UnknownOutputParams; } | { pathname: `/Passenger/PassengerOnTravel`; params?: Router.UnknownOutputParams; } | { pathname: `/Passenger/Passengerrideroffers`; params?: Router.UnknownOutputParams; } | { pathname: `/Passenger/PassengerSearchRider`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/ChooseModeScreen${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/register${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/Driver/DriverHomePage${`?${string}` | `#${string}` | ''}` | `/Driver/DriverOnTravel${`?${string}` | `#${string}` | ''}` | `/Driver/DriverTravel${`?${string}` | `#${string}` | ''}` | `/Driver/PublishTravel${`?${string}` | `#${string}` | ''}` | `/Driver/RequestTravelDriver${`?${string}` | `#${string}` | ''}` | `/Passenger/PassengerConfirmation${`?${string}` | `#${string}` | ''}` | `/Passenger/PassengerConfirmRider${`?${string}` | `#${string}` | ''}` | `/Passenger/PassengerDriverProfile${`?${string}` | `#${string}` | ''}` | `/Passenger/PassengerHomePage${`?${string}` | `#${string}` | ''}` | `/Passenger/PassengerOnTravel${`?${string}` | `#${string}` | ''}` | `/Passenger/Passengerrideroffers${`?${string}` | `#${string}` | ''}` | `/Passenger/PassengerSearchRider${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/ChooseModeScreen`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/register`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/Driver/DriverHomePage`; params?: Router.UnknownInputParams; } | { pathname: `/Driver/DriverOnTravel`; params?: Router.UnknownInputParams; } | { pathname: `/Driver/DriverTravel`; params?: Router.UnknownInputParams; } | { pathname: `/Driver/PublishTravel`; params?: Router.UnknownInputParams; } | { pathname: `/Driver/RequestTravelDriver`; params?: Router.UnknownInputParams; } | { pathname: `/Passenger/PassengerConfirmation`; params?: Router.UnknownInputParams; } | { pathname: `/Passenger/PassengerConfirmRider`; params?: Router.UnknownInputParams; } | { pathname: `/Passenger/PassengerDriverProfile`; params?: Router.UnknownInputParams; } | { pathname: `/Passenger/PassengerHomePage`; params?: Router.UnknownInputParams; } | { pathname: `/Passenger/PassengerOnTravel`; params?: Router.UnknownInputParams; } | { pathname: `/Passenger/Passengerrideroffers`; params?: Router.UnknownInputParams; } | { pathname: `/Passenger/PassengerSearchRider`; params?: Router.UnknownInputParams; };
    }
  }
}
